# Generated by Django 5.2.4 on 2025-10-14 07:18

import django.db.models.deletion
import pelatihan.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('konfigurasi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelatihan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255, verbose_name='Judul Pelatihan')),
                ('tanggal_mulai', models.DateField(verbose_name='Tanggal Mulai Pelatihan')),
                ('tanggal_selesai', models.DateField(verbose_name='Tanggal Selesai Pelatihan')),
                ('durasi', models.PositiveSmallIntegerField(verbose_name='Durasi Pelatihan')),
                ('pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pelatihan', to=settings.AUTH_USER_MODEL, verbose_name='PIC Pelatihan')),
            ],
        ),
        migrations.CreateModel(
            name='PelatihanDokumen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(choices=[('00', 'Daftar Riwayat Hidup Peserta'), ('01', 'Nominatif Peserta'), ('02', 'Daftar Hadir Peserta'), ('03', 'Daftar Hadir Instruktur'), ('04', 'Jadwal Pelatihan'), ('05', 'Daftar Jam Mengajar Instruktur'), ('06', 'Daftar Nilai Akhir'), ('07', 'Tanda Terima ATK Peserta + ID Card'), ('08', 'Tanda Terima Pakaian Kerja/Kaos Olahraga+Training'), ('09', 'Tanda Terima Sepatu Kerja'), ('10', 'Tanda Terima Modul'), ('11', 'Tanda Terima Bahan Pelatihan'), ('12', 'Tanda Terima Konsumsi'), ('13', 'Fotocopy Sertifikat Pelatihan'), ('14', 'Dokumentasi Kegiatan')], max_length=2, verbose_name='Jenis Dokumen')),
                ('file_url', models.FileField(blank=True, null=True, upload_to=pelatihan.models.upload_to_dokumen, verbose_name='URL Dokumen')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes Admin')),
                ('pelatihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen', to='pelatihan.pelatihan')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='konfigurasi.statusdokumen', verbose_name='Status Dokumen')),
            ],
            options={
                'unique_together': {('pelatihan', 'nama')},
            },
        ),
    ]
