# Generated by Django 5.2.4 on 2025-08-20 02:02

import django.db.models.deletion
import pelatihan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelatihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255, verbose_name='Judul Pelatihan')),
                ('tanggal_mulai', models.DateField(verbose_name='Tanggal Mulai Pelatihan')),
                ('tanggal_selesai', models.DateField(verbose_name='Tanggal Selesai Pelatihan')),
                ('durasi', models.PositiveSmallIntegerField(verbose_name='Durasi Pelatihan')),
                ('pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pelatihan', to='accounts.profile', verbose_name='PIC Pelatihan')),
            ],
        ),
        migrations.CreateModel(
            name='PelatihanDokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(choices=[('00', 'DokumenO'), ('01', 'DokumenN'), ('02', 'DokumenM'), ('03', 'DokumenL'), ('04', 'DokumenK'), ('05', 'DokumenJ'), ('06', 'DokumenI'), ('07', 'DokumenH'), ('08', 'DokumenG'), ('09', 'DokumenF'), ('10', 'DokumenE'), ('11', 'DokumenD'), ('12', 'DokumenC'), ('13', 'DokumenB'), ('14', 'DokumenA')], max_length=2, verbose_name='Jenis Dokumen')),
                ('status', models.CharField(choices=[('0', 'Kosong'), ('1', 'Sedang Diverifikasi'), ('2', 'Perlu Revisi'), ('3', 'Terverifikasi')], default='0', max_length=1, verbose_name='Status Dokumen')),
                ('file_url', models.FileField(blank=True, upload_to=pelatihan.models.upload_to_dokumen, verbose_name='URL Dokumen')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes Admin')),
                ('pelatihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen', to='pelatihan.pelatihan')),
            ],
        ),
    ]
