# Generated by Django 5.2.4 on 2025-11-04 04:36

import django.db.models.deletion
import pelatihan.models
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('konfigurasi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruktur',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=22, max_length=22, prefix='', primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Lengkap Instruktur')),
                ('kejuruan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instruktur_set', to='konfigurasi.kejuruan', verbose_name='Kejuruan Utama')),
            ],
            options={
                'verbose_name': 'Instruktur',
                'verbose_name_plural': 'Daftar Instruktur',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Pelatihan',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=22, max_length=22, prefix='', primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255, verbose_name='Program Pelatihan')),
                ('paket_ke', models.PositiveSmallIntegerField(verbose_name='Paket Ke-')),
                ('tanggal_mulai_rencana', models.DateField(verbose_name='Tanggal Mulai (Rencana)')),
                ('tanggal_selesai_rencana', models.DateField(verbose_name='Tanggal Selesai (Rencana)')),
                ('jenis_pelatihan', models.CharField(blank=True, choices=[('BOARDING', 'Boarding'), ('NON_BOARDING', 'Non-Boarding')], max_length=15, verbose_name='Jenis Pelatihan')),
                ('metode', models.CharField(blank=True, choices=[('INSTITUTIONAL', 'Institutional'), ('MTU', 'MTU')], max_length=15, verbose_name='Metode Pelatihan')),
                ('tempat_pelaksanaan', models.CharField(blank=True, max_length=255)),
                ('tanggal_mulai_aktual', models.DateField(blank=True, null=True, verbose_name='Tanggal Mulai (Aktual)')),
                ('tanggal_selesai_aktual', models.DateField(blank=True, null=True, verbose_name='Tanggal Selesai (Aktual)')),
                ('durasi_jp', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Durasi Pelatihan (JP)')),
                ('jam_per_hari', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Jam Pelajaran per Hari')),
                ('waktu_pelatihan', models.CharField(blank=True, help_text='Contoh: 08:00 s.d. 16:00', max_length=100, verbose_name='Waktu Pelaksanaan')),
                ('no_sk', models.CharField(blank=True, max_length=255, verbose_name='Nomor SK Penyelenggaraan')),
                ('tanggal_sk', models.DateField(blank=True, null=True, verbose_name='Tanggal SK Penyelenggaraan')),
                ('tentang_sk', models.TextField(blank=True, verbose_name='Tentang SK')),
                ('jabatan_penandatangan', models.CharField(blank=True, max_length=255, verbose_name='Nama Jabatan Ttd. Laporan')),
                ('nama_penandatangan', models.CharField(blank=True, max_length=255, verbose_name='Nama Pejabat Ttd. Laporan')),
                ('nip_penandatangan', models.CharField(blank=True, max_length=50, verbose_name='NIP Pejabat Ttd. Laporan')),
                ('tanggal_penandatangan', models.DateField(blank=True, null=True, verbose_name='Tanggal Ttd Laporan')),
                ('jumlah_peserta_laki', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Jumlah Peserta Laki-Laki')),
                ('jumlah_peserta_perempuan', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Jumlah Peserta Perempuan')),
                ('jumlah_lulus', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Jumlah Lulus')),
                ('jumlah_belum_lulus', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Jumlah Belum Lulus')),
                ('alasan_belum_lulus', models.TextField(blank=True)),
                ('rata_rata_pendidikan', models.CharField(blank=True, help_text='Contoh: SMA', max_length=100, verbose_name='Rata-Rata Pendidikan Peserta')),
                ('rata_rata_usia', models.FloatField(blank=True, help_text='Contoh: 25.3', null=True, verbose_name='Rata-Rata Usia Peserta')),
                ('rata_rata_domisili', models.CharField(blank=True, help_text='Contoh: Bekasi', max_length=255, verbose_name='Rata-Rata Domisili Peserta')),
                ('keterangan_lanjutan', models.TextField(blank=True, verbose_name='Keterangan Lanjutan')),
                ('progress_laporan', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Progres Laporan (%)')),
                ('kejuruan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pelatihan', to='konfigurasi.kejuruan')),
                ('penyelenggara', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pelatihan', to=settings.AUTH_USER_MODEL, verbose_name='Penyelenggara (PIC)')),
                ('tahun_anggaran', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pelatihan', to='konfigurasi.tahunanggaran')),
            ],
        ),
        migrations.CreateModel(
            name='PelatihanInstruktur',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=22, max_length=22, prefix='', primary_key=True, serialize=False)),
                ('materi', models.TextField(verbose_name='Materi yang Diajarkan')),
                ('instruktur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materi_diajar', to='pelatihan.instruktur')),
                ('pelatihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruktur_set', to='pelatihan.pelatihan')),
            ],
            options={
                'verbose_name': 'Instruktur Pelatihan',
                'verbose_name_plural': 'Daftar Instruktur Pelatihan',
                'unique_together': {('pelatihan', 'instruktur', 'materi')},
            },
        ),
        migrations.CreateModel(
            name='PelatihanLampiran',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=22, max_length=22, prefix='', primary_key=True, serialize=False)),
                ('nama', models.CharField(choices=[('00', 'Daftar Riwayat Hidup Peserta'), ('01', 'Nominatif Peserta'), ('02', 'Daftar Hadir Peserta'), ('03', 'Daftar Hadir Instruktur'), ('04', 'Jadwal Pelatihan'), ('05', 'Daftar Jam Mengajar Instruktur'), ('06', 'Daftar Nilai Akhir'), ('07', 'Tanda Terima ATK Peserta + ID Card'), ('08', 'Tanda Terima Pakaian Kerja/Kaos Olahraga+Training'), ('09', 'Tanda Terima Sepatu Kerja'), ('10', 'Tanda Terima Modul'), ('11', 'Tanda Terima Bahan Pelatihan'), ('12', 'Tanda Terima Konsumsi'), ('13', 'Fotocopy Sertifikat Pelatihan'), ('14', 'Dokumentasi Kegiatan')], max_length=2, verbose_name='Jenis Dokumen')),
                ('file_url', models.FileField(blank=True, null=True, upload_to=pelatihan.models.upload_to_dokumen, verbose_name='URL Dokumen')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes Admin')),
                ('pelatihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen', to='pelatihan.pelatihan')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='konfigurasi.statusdokumen', verbose_name='Status Dokumen')),
            ],
            options={
                'ordering': ['nama'],
                'unique_together': {('pelatihan', 'nama')},
            },
        ),
    ]
