# Generated by Django 4.2.21 on 2025-06-03 04:14

from django.db import migrations, models
import django.db.models.deletion
import pelatihan.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_foto'),
        ('pelatihan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelatihandokumen',
            name='file',
        ),
        migrations.AddField(
            model_name='pelatihandokumen',
            name='docs',
            field=models.FileField(default='test.pdf', upload_to=pelatihan.models.upload_to_dokumen, verbose_name='Dokumen yang Diupload'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pelatihan',
            name='pic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pelatihan', to='accounts.profile', verbose_name='PIC Pelatihan'),
        ),
        migrations.AlterField(
            model_name='pelatihandokumen',
            name='nama',
            field=models.CharField(choices=[('01', 'DokumenO'), ('02', 'DokumenN'), ('03', 'DokumenM'), ('04', 'DokumenL'), ('05', 'DokumenK'), ('06', 'DokumenJ'), ('07', 'DokumenI'), ('08', 'DokumenH'), ('09', 'DokumenG'), ('10', 'DokumenF'), ('11', 'DokumenE'), ('12', 'DokumenD'), ('13', 'DokumenC'), ('14', 'DokumenB'), ('15', 'DokumenA')], max_length=2, verbose_name='Jenis Dokumen'),
        ),
    ]
