# Generated by Django 5.2.4 on 2025-10-28 08:20

from django.db import migrations

INSTRUKTUR_DATA = [
    {'kejuruan_id': 'ELK', 'nama': 'Adi Suroso, S.T., M.Si'},
    {'kejuruan_id': 'ELK', 'nama': 'Mulyo Pujihadi, S.T.,M.T.'},
    {'kejuruan_id': 'ELK', 'nama': 'Robert Wesley Sihar Sirait, S.T., M.Si.'},
    {'kejuruan_id': 'ELK', 'nama': 'Dedi Kardiaman, S.T.'},
    {'kejuruan_id': 'ELK', 'nama': 'Suyanta, S.T., M.T.'},
    {'kejuruan_id': 'ELK', 'nama': 'Yuriyandi Feryantasum Eko Haryono ST, M.Si'},
    {'kejuruan_id': 'ELK', 'nama': 'Andrianus John Richard, S.T., M.Si'},
    {'kejuruan_id': 'ELK', 'nama': 'Albertus Agung Femin Himawan, S.T., M.T.'},
    {'kejuruan_id': 'LAS', 'nama': 'Oktosa Indriatmoko, S.T.'},
    {'kejuruan_id': 'LAS', 'nama': 'Ayani Karunia Putra, S.T.'},
    {'kejuruan_id': 'TIK', 'nama': 'Daniel L. Tobing, S.Pd'},
    {'kejuruan_id': 'TIK', 'nama': 'Nanang Baidowi, S.S., M.Si'},
    {'kejuruan_id': 'TIK', 'nama': 'Prasetyo Madyo Utomo, S.T.,M.T.'},
    {'kejuruan_id': 'TIK', 'nama': 'Singgih Prabowo, S.T.'},
    {'kejuruan_id': 'TIK', 'nama': 'Endes Runi Anisah, S.S., M.A'},
    {'kejuruan_id': 'REF', 'nama': 'Sri Hardono, S.T., M.Sc'},
    {'kejuruan_id': 'REF', 'nama': 'Abdul Hadi, S.T.'},
    {'kejuruan_id': 'REF', 'nama': 'Mangiring Sitorus, S.Pd., M.Pd.'},
    {'kejuruan_id': 'TIK', 'nama': 'Ardani Titi Sari, S.S., M.Sc.'},
    {'kejuruan_id': 'TIK', 'nama': 'Ceriani, S.E.I., M.Sc.'},
    {'kejuruan_id': 'ELK', 'nama': 'Taqwa Zadana,S.Pd'},
    {'kejuruan_id': 'ELK', 'nama': 'Heru Khairul Khabibie, S.T.'},
    {'kejuruan_id': 'ELK', 'nama': 'Agustinus Manguntam, S.T.'},
    {'kejuruan_id': 'ELK', 'nama': 'Indra Prasetyawan, S.T.'},
    {'kejuruan_id': 'ELK', 'nama': 'Umul Masrianah, S.T.'},
    {'kejuruan_id': 'ELK', 'nama': 'Eko Wahyuning Pamungkas, S.T., M.T.'},
    {'kejuruan_id': 'ELK', 'nama': 'Barita Martupa Nababan, S.T.'},
    {'kejuruan_id': 'ELK', 'nama': 'Devia Eka Yunida, S.T., M.Eng.'},
    {'kejuruan_id': 'LAS', 'nama': 'Artos Evit, S.T.'},
    {'kejuruan_id': 'TIK', 'nama': 'Abdullah Arif, S.E.'},
    {'kejuruan_id': 'TIK', 'nama': 'Fauzia Rizkiana Aji, S.T., M.T.'},
    {'kejuruan_id': 'TIK', 'nama': 'Reza Putra Wirawan, S.I.Kom.'},
    {'kejuruan_id': 'TIK', 'nama': 'Farhan Tri Arsyad, S.Kom'},
    {'kejuruan_id': 'TIK', 'nama': 'Syamsiah, S.T.'},
    {'kejuruan_id': 'TIK', 'nama': 'Wahyu Pratomo, S.Psi.'},
    {'kejuruan_id': 'TIK', 'nama': 'Dewi Herawati, B.Eng., M.T.'},
    {'kejuruan_id': 'TIK', 'nama': 'Avicenna Hamdan, S.T.'},
    {'kejuruan_id': 'TIK', 'nama': 'Etik Noor Rochmah, S.S., M.Si.'},
    {'kejuruan_id': 'TIK', 'nama': 'Artha Puspa Indah, S.S.'},
    {'kejuruan_id': 'TIK', 'nama': 'Rina Dwiana, S.S., M.Si.'},
    {'kejuruan_id': 'TIK', 'nama': 'Raditia Linuria Mardika, S.E.'},
    {'kejuruan_id': 'TIK', 'nama': 'Kristina Dewi, S.T.'},
    {'kejuruan_id': 'TIK', 'nama': 'Desmaria Syahril, S.S.'},
    {'kejuruan_id': 'REF', 'nama': 'Andy Karlam, S.T.'},
    {'kejuruan_id': 'REF', 'nama': 'Dwi Nuryanto, S.Pd.I'},
    {'kejuruan_id': 'REF', 'nama': 'Gina Verina, S.Pd'},
    {'kejuruan_id': 'TIK', 'nama': 'Cika Herdanis, S.Kom.'},
    {'kejuruan_id': 'ELK', 'nama': 'Husni Hamdani, S.T.'},
    {'kejuruan_id': 'ELK', 'nama': 'Hasrul Baki Hasibuan, S.T.'},
    {'kejuruan_id': 'ELK', 'nama': 'Rahmat Arifiyanto, S.T.'},
    {'kejuruan_id': 'ELK', 'nama': 'Rio Hermawan, S.T.'},
    {'kejuruan_id': 'ELK', 'nama': 'Noftha Rizal, S.T.'},
    {'kejuruan_id': 'ELK', 'nama': 'Arya Wiguna Bangun, S.T.'},
    {'kejuruan_id': 'ELK', 'nama': 'Bian Hardiyanto, S.T.'},
    {'kejuruan_id': 'ELK', 'nama': 'Farid Rinanto, S.ST.'},
    {'kejuruan_id': 'LAS', 'nama': 'R. Muslim Hidayatullah, S.T.'},
    {'kejuruan_id': 'TIK', 'nama': 'Zulka Ali Ajuab, S.Kom.'},
    {'kejuruan_id': 'TIK', 'nama': 'RM. Muhammad Whisnu Teguh Nugroho, S.T'},
    {'kejuruan_id': 'TIK', 'nama': 'Muhamad Yusuf Ibrahim, A.Md'},
    {'kejuruan_id': 'TIK', 'nama': 'Yani Mulyani, S.Sos'},
    {'kejuruan_id': 'TIK', 'nama': 'Candra Hadi Nugroho, S.T.,M.T'},
    {'kejuruan_id': 'TIK', 'nama': 'Tri Handayani, ST.'},
    {'kejuruan_id': 'TIK', 'nama': 'Arso Bagus Setiawan, S.T.'},
    {'kejuruan_id': 'TIK', 'nama': 'Defy Ayu Manalu, S.Si.Kom'},
    {'kejuruan_id': 'TIK', 'nama': 'Dwi Irfan Pambudi, S.T.'},
    {'kejuruan_id': 'TIK', 'nama': 'Rusdi Hamdani Hutasuhut, S.SI.'},
    {'kejuruan_id': 'TIK', 'nama': 'Bondan Sedyo Wicaksono, S.Kom'},
    {'kejuruan_id': 'TIK', 'nama': 'Faisal Rahman, S.Kom.'},
    {'kejuruan_id': 'TIK', 'nama': 'Jeanny Fatma Mutmainnah, S.Kom.'},
    {'kejuruan_id': 'TIK', 'nama': 'Yiswi Nilam Prastikasari, S.Kom.'},
    {'kejuruan_id': 'TIK', 'nama': 'Destra Ricko, S.S.'},
    {'kejuruan_id': 'REF', 'nama': 'Junica Dumaria Simanjuntak, ST'},
    {'kejuruan_id': 'PAR', 'nama': 'Wirawan Albertus, S.I.Kom.'},
    {'kejuruan_id': 'PAR', 'nama': 'Fahim Ahmada, S.I.Kom.'},
    {'kejuruan_id': 'PAR', 'nama': 'Rahadian Muslim, S.ST.Par'},
    {'kejuruan_id': 'PAR', 'nama': 'Wanda Seimahuira, S.Tr.Par.'},
    {'kejuruan_id': 'PAR', 'nama': 'Annisaa Aulia, S.ST.Par'},
    {'kejuruan_id': 'PAR', 'nama': 'Galih Prassetya, S.ST.Par.,M.Par.'},
    {'kejuruan_id': 'PAR', 'nama': 'Ricky Bayuandry Fernando, SST.'},
    {'kejuruan_id': 'PAR', 'nama': 'Ria Krisnasari, S.ST. Par.'},
    {'kejuruan_id': 'PAR', 'nama': 'Irawaty Susila, S.ST.Par.'},
    {'kejuruan_id': 'PAR', 'nama': 'Susi Safra Dewi, SST.'},
    {'kejuruan_id': 'PAR', 'nama': 'Sithy Fatimah, S.S.T.,M.Par.'},
    {'kejuruan_id': 'ELK', 'nama': 'Marlusia Wita, S.T., M.Sc.'},
    {'kejuruan_id': 'TIK', 'nama': 'Septian Rizky Sinaga, S.Kom.'},
    {'kejuruan_id': 'TIK', 'nama': 'Repa Sugiarto, S.T.'},
    {'kejuruan_id': 'TIK', 'nama': 'Robe Manjaya, S.T'},
    {'kejuruan_id': 'TIK', 'nama': 'M. Alfie Ridwan, S.Kom.'},
    {'kejuruan_id': 'TIK', 'nama': 'Setyo Wahyu Utomo, S.T.'},
    {'kejuruan_id': 'REF', 'nama': 'Heru Hermawan, S.T'},
    {'kejuruan_id': 'REF', 'nama': 'Eri Noviar, A.Md'},
    {'kejuruan_id': 'PAR', 'nama': 'Dhuha Zaskia Alisa, S.Sos'},
    {'kejuruan_id': 'PAR', 'nama': 'Sifa Damayanti, A.Md'},
    {'kejuruan_id': 'PAR', 'nama': 'Ester Yuanysia, A.Md.Par'},
    {'kejuruan_id': 'ELK', 'nama': 'Inne Nur Septiani, A.Md.'},
    {'kejuruan_id': 'PAR', 'nama': 'Haris Imam Setyawan, A.Md'},
    {'kejuruan_id': 'PAR', 'nama': 'Brigitta Ditta Hapsari, A.Md.'}
]

def create_initial_instruktur(apps, schema_editor):
    Instruktur = apps.get_model('pelatihan', 'Instruktur')
    Kejuruan = apps.get_model('konfigurasi', 'Kejuruan') # Perlu untuk validasi

    for data in INSTRUKTUR_DATA:
        # Pastikan kejuruan ada sebelum membuat instruktur
        try:
            kejuruan = Kejuruan.objects.get(pk=data['kejuruan_id'])
            Instruktur.objects.get_or_create(
                nama=data['nama'], 
                defaults={'kejuruan': kejuruan}
            )
        except Kejuruan.DoesNotExist:
            print(f"Peringatan: Kejuruan dengan ID '{data['kejuruan_id']}' tidak ditemukan. Instruktur '{data['nama']}' tidak dibuat.")

class Migration(migrations.Migration):


    dependencies = [
        ('pelatihan', '0002_fix_mariadb_fk'),
        ('konfigurasi', '0003_populate_kejuruan'),
    ]

    operations = [
        migrations.RunPython(create_initial_instruktur),
    ]
