# Generated by Django 5.2.4 on 2025-11-06 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konfigurasi', '0005_statuspelatihan'),
        ('pelatihan', '0002_populate_instruktur'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelatihan',
            name='nama_lembaga_pelaksana',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pelatihan',
            name='progress_upload',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Progres Upload (%)'),
        ),
        migrations.AddField(
            model_name='pelatihan',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='status', to='konfigurasi.statuspelatihan', verbose_name='Status Pelatihan'),
        ),
        migrations.AlterField(
            model_name='pelatihan',
            name='metode',
            field=models.CharField(blank=True, choices=[('IN', 'Dalam Balai'), ('OUT', 'Luar Balai')], max_length=3, verbose_name='Metode Pelatihan'),
        ),
    ]
