# Generated by Django 4.2.21 on 2025-06-03 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelatihan', '0002_remove_pelatihandokumen_file_pelatihandokumen_docs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelatihandokumen',
            old_name='docs',
            new_name='uploaded',
        ),
    ]
