# Generated by Django 5.2.4 on 2025-11-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelatihan', '0002_populate_instruktur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelatihanlampiran',
            options={'ordering': ['nama']},
        ),
        migrations.AddField(
            model_name='pelatihan',
            name='progress_laporan',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Progres Laporan (%)'),
        ),
    ]
