# Generated by Django 4.2.21 on 2025-06-03 06:16

from django.db import migrations, models
import pelatihan.models


class Migration(migrations.Migration):

    dependencies = [
        ('pelatihan', '0003_rename_docs_pelatihandokumen_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelatihandokumen',
            name='uploaded',
        ),
        migrations.AddField(
            model_name='pelatihandokumen',
            name='file_url',
            field=models.FileField(default='nama.pdf', upload_to=pelatihan.models.upload_to_dokumen, verbose_name='URL Dokumen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pelatihandokumen',
            name='status',
            field=models.CharField(choices=[('0', 'Kosong'), ('1', 'Sedang Diverifikasi'), ('2', 'Perlu Revisi'), ('3', 'Terverifikasi')], default='0', max_length=1, verbose_name='Status Dokumen'),
        ),
        migrations.AlterField(
            model_name='pelatihandokumen',
            name='nama',
            field=models.CharField(choices=[('00', 'DokumenO'), ('01', 'DokumenN'), ('02', 'DokumenM'), ('03', 'DokumenL'), ('04', 'DokumenK'), ('05', 'DokumenJ'), ('06', 'DokumenI'), ('07', 'DokumenH'), ('08', 'DokumenG'), ('09', 'DokumenF'), ('10', 'DokumenE'), ('11', 'DokumenD'), ('12', 'DokumenC'), ('13', 'DokumenB'), ('14', 'DokumenA')], max_length=2, verbose_name='Jenis Dokumen'),
        ),
    ]
