# Generated by Django 4.2.21 on 2025-06-10 01:30

from django.db import migrations, models
import pelatihan.models


class Migration(migrations.Migration):

    dependencies = [
        ('pelatihan', '0004_remove_pelatihandokumen_uploaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelatihandokumen',
            name='notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='Notes Admin'),
        ),
        migrations.AlterField(
            model_name='pelatihandokumen',
            name='file_url',
            field=models.FileField(blank=True, upload_to=pelatihan.models.upload_to_dokumen, verbose_name='URL Dokumen'),
        ),
    ]
