# Generated by Django 5.2.4 on 2025-08-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelatihan', '0005_pelatihandokumen_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelatihandokumen',
            name='nama',
            field=models.CharField(choices=[('00', 'Daftar Riwayat Hidup Peserta'), ('01', 'Nominatif Peserta'), ('02', 'Daftar Hadir Peserta'), ('03', 'Daftar Hadir Instruktur'), ('04', 'Jadwal Pelatihan'), ('05', 'Daftar Jam Mengajar Instruktur'), ('06', 'Daftar Nilai Akhir'), ('07', 'Tanda Terima ATK Peserta + ID Card'), ('08', 'Tanda Terima Pakaian Kerja/Kaos Olahraga+Training'), ('09', 'Tanda Terima Sepatu Kerja'), ('10', 'Tanda Terima Modul'), ('11', 'Tanda Terima Bahan Pelatihan'), ('12', 'Tanda Terima Konsumsi'), ('13', 'Fotocopy Sertifikat Pelatihan'), ('14', 'Dokumentasi Kegiatan')], max_length=2, verbose_name='Jenis Dokumen'),
        ),
    ]
