# Generated by Django 5.2.4 on 2025-10-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(help_text='Contoh: AD, PL', max_length=2, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TahunAnggaran',
            fields=[
                ('tahun', models.PositiveIntegerField(help_text='Tahun anggaran, contoh: 2025', primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('AKTIF', 'Aktif'), ('DITUTUP', 'Ditutup'), ('DIARSIPKAN', 'Diarsipkan')], default='AKTIF', help_text="Status tahun anggaran (hanya pelatihan dengan tahun berstatus 'Aktif' yang bisa dibuat)", max_length=10)),
                ('keterangan', models.TextField(blank=True, help_text='Catatan atau keterangan tambahan untuk tahun anggaran ini', null=True)),
            ],
            options={
                'verbose_name': 'Tahun Anggaran',
                'verbose_name_plural': 'Daftar Tahun Anggaran',
                'ordering': ['-tahun'],
            },
        ),
    ]
