# Generated by Django 5.2.4 on 2025-11-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kejuruan',
            fields=[
                ('id', models.CharField(help_text='Contoh: TIK, LAS', max_length=3, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(help_text='Contoh: AD, PL', max_length=2, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusDokumen',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50, unique=True)),
                ('keterangan', models.TextField(blank=True, help_text='Deskripsi singkat mengenai status ini.')),
            ],
            options={
                'verbose_name': 'Status Dokumen',
                'verbose_name_plural': 'Daftar Status Dokumen',
            },
        ),
        migrations.CreateModel(
            name='TahunAnggaran',
            fields=[
                ('tahun', models.PositiveIntegerField(help_text='Tahun anggaran, contoh: 2025', primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('AKTIF', 'Aktif'), ('DITUTUP', 'Ditutup'), ('DIARSIPKAN', 'Diarsipkan')], default='AKTIF', help_text="Status tahun anggaran (hanya pelatihan dengan tahun berstatus 'Aktif' yang bisa dibuat)", max_length=10)),
                ('target', models.PositiveIntegerField(default=0, help_text='Jumlah target paket pelatihan untuk tahun anggaran ini.', verbose_name='Target Paket Pelatihan')),
                ('keterangan', models.TextField(blank=True, help_text='Catatan atau keterangan tambahan untuk tahun anggaran ini', null=True)),
            ],
            options={
                'verbose_name': 'Tahun Anggaran',
                'verbose_name_plural': 'Daftar Tahun Anggaran',
                'ordering': ['-tahun'],
            },
        ),
    ]
