# Generated by Django 5.2.4 on 2025-10-07 07:33

from django.db import migrations


ROLES_DATA = [
    {'id': 'AD', 'nama': 'Admin'},
    {'id': 'PL', 'nama': 'Penyelenggara'},
]

def create_initial_roles(apps, schema_editor):
    Role = apps.get_model('konfigurasi', 'Role')
    for role_data in ROLES_DATA:
        Role.objects.create(**role_data)

class Migration(migrations.Migration):
    dependencies = [
        ('konfigurasi', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(create_initial_roles),
    ]
