# Generated by Django 5.2.4 on 2025-10-24 11:35

from django.db import migrations

KEJURUAN_DATA = [
    {'id': 'TIK', 'nama': 'TIK'},
    {'id': 'LAS', 'nama': 'Welding'},
    {'id': 'ELK', 'nama': 'Elektronika'},
    {'id': 'PAR', 'nama': 'Pariwisata'},
    {'id': 'REF', 'nama': 'Refrigeration'},
]

def create_initial_kejuruans(apps, schema_editor):
    Kejuruan = apps.get_model('konfigurasi', 'Kejuruan')
    for kejuruan_data in KEJURUAN_DATA:
        Kejuruan.objects.create(**kejuruan_data)

class Migration(migrations.Migration):

    dependencies = [
        ('konfigurasi', '0002_populate_role'),
    ]

    operations = [
        migrations.RunPython(create_initial_kejuruans)
    ]
