# Generated by Django 5.2.4 on 2025-10-24 12:21

from django.db import migrations


# Generated by Django 5.2.4 on 2025-10-07 07:33

from django.db import migrations


STATUS_DOKUMEN_DATA = [
    {'id': 1, 'nama': 'Kosong'},
    {'id': 2, 'nama': 'Dalam Proses Verifikasi'},
    {'id': 3, 'nama': 'Perlu Revisi'},
    {'id': 4, 'nama': 'Terverifikasi'},
]

def create_initial_status_dokumens(apps, schema_editor):
    StatusDokumen = apps.get_model('konfigurasi', 'StatusDokumen')
    for status_dokumen_data in STATUS_DOKUMEN_DATA:
        StatusDokumen.objects.create(**status_dokumen_data)

class Migration(migrations.Migration):
    dependencies = [
        ('konfigurasi', '0003_populate_kejuruan'),
    ]
    
    operations = [
        migrations.RunPython(create_initial_status_dokumens),
    ]
