# Generated by Django 5.2.4 on 2025-11-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konfigurasi', '0004_populate_status_dokumen'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPelatihan',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50, unique=True)),
                ('keterangan', models.TextField(blank=True, help_text='Deskripsi singkat mengenai status ini.')),
            ],
            options={
                'verbose_name': 'Status Pelatihan',
                'verbose_name_plural': 'Daftar Status Pelatihan',
            },
        ),
    ]
