# Generated by Django 5.2.4 on 2025-10-24 12:21

from django.db import migrations


# Generated by Django 5.2.4 on 2025-10-07 07:33

from django.db import migrations


STATUS_PELATIHAN_DATA = [
    {'id': 1, 'nama': 'Belum Berjalan'},
    {'id': 2, 'nama': 'Sedang Berjalan'},
    {'id': 3, 'nama': 'Selesai'},
]

def create_initial_status_pelatihans(apps, schema_editor):
    StatusPelatihan = apps.get_model('konfigurasi', 'StatusPelatihan')
    for status_pelatihan_data in STATUS_PELATIHAN_DATA:
        StatusPelatihan.objects.create(**status_pelatihan_data)

class Migration(migrations.Migration):
    dependencies = [
        ('konfigurasi', '0005_statuspelatihan'),
    ]
    
    operations = [
        migrations.RunPython(create_initial_status_pelatihans),
    ]
